apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-15T16:50:57Z"
  generation: 2
  labels:
    app: lizard
  name: lizard
  namespace: default
  resourceVersion: "22479"
  selfLink: /apis/apps/v1/namespaces/default/deployments/lizard
  uid: 337df2fe-37b7-11ea-a8c2-42010a80014a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lizard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lizard
    spec:
      containers:
      - image: gcr.io/kuberneteschallenge/k8:latest
        imagePullPolicy: Always
        name: k8
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-15T16:51:34Z"
    lastUpdateTime: "2020-01-15T16:51:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-15T16:50:57Z"
    lastUpdateTime: "2020-01-15T16:51:34Z"
    message: ReplicaSet "lizard-5557699d85" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
